cd(@__DIR__)
include("Parser.jl")
stream = open("my_model_with_functions.stan","r")
#stream = open("my_model.stan","r")
model = read(stream,String)
close(stream)
println("---Original model---")
println()
println(model)
println()
str = includeCommand(model)
if !isempty(str)
    #parse if there is an include command
    model = addFunctions(str,model)
end
println("---Updated model---")
println()
println(model)
println()
